// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Infrastructure.Context;

#nullable disable

namespace ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260627063037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 6, 27, 6, 30, 36, 988, DateTimeKind.Utc).AddTicks(7112),
                            Description = "Classic blue denim jeans for everyday wear",
                            ImageUrl = "https://example.com/jeans.jpg",
                            IsActive = true,
                            Name = "Blue Denim Jeans",
                            Price = 59.99m,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2026, 6, 27, 6, 30, 36, 988, DateTimeKind.Utc).AddTicks(7115)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 6, 27, 6, 30, 36, 988, DateTimeKind.Utc).AddTicks(7122),
                            Description = "Premium cotton white t-shirt",
                            ImageUrl = "https://example.com/tshirt.jpg",
                            IsActive = true,
                            Name = "White T-Shirt",
                            Price = 24.99m,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2026, 6, 27, 6, 30, 36, 988, DateTimeKind.Utc).AddTicks(7122)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
